version: '3.3'
services:
  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: Pa55word123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    healthcheck:
      test: sqlcmd -S localhost -U SA -P 'Pa55word123!'   -Q 'select 1'

